name: SpawnerCollector
version: 1.0
main: com.iain.spawnercollector.Main
api-version: 1.14
commands:
  crowbar:
    description: get a crowbar item
    permission: arcwood.crowbar
    usage: /crowbar [player name] [amount] 